### ISSUE TITLE
Tester for outdoor camera and doorbell

### ISSUE THREAD

**Issue by jmjlai** [anzure/homebridge-netatmo-security#14]
I can be a tester for outdoor camera and doorbell uses, but my plugin seems to crash on trying to read the properties of 'home'.
my home is not named 'home' in the netatmo security app, is this hardcoded?

**Logs:**

```
[10/22/2022, 9:17:10 PM] [Netatmo Security Platform] Child bridge process ended
[10/22/2022, 9:17:10 PM] [Netatmo Security Platform] Process Ended. Code: 1, Signal: null
[10/22/2022, 9:17:17 PM] [Netatmo Security Platform] Restarting Process...
[10/22/2022, 9:17:19 PM] [Netatmo Security Platform] Launched child bridge with PID 10605
[10/22/2022, 9:17:19 PM] Registering platform 'homebridge-netatmo-security.netatmo-security'
[10/22/2022, 9:17:19 PM] [Netatmo Security Platform] Loaded homebridge-netatmo-security v1.2.1 child bridge successfully
[10/22/2022, 9:17:19 PM] [Netatmo Security Platform] Netatmo API constructed.
[10/22/2022, 9:17:20 PM] Homebridge v1.5.0 (HAP v0.10.2) (Netatmo Security Platform) is running on port *****.
TypeError: Cannot read properties of undefined (reading 'home')
    at NetatmoAPI.getHomeStatus (/homebridge/node_modules/homebridge-netatmo-security/src/util/NetatmoAPI.js:102:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at NetatmoAPI.getHomeDevices (/homebridge/node_modules/homebridge-netatmo-security/src/util/NetatmoAPI.js:110:20)
[10/22/2022, 9:17:22 PM] [Netatmo Security Platform] Child bridge process ended```

**Plugin Config:**

```json
        {
            "name": "Netatmo Security Platform",
            "client_id": "***",
            "client_secret": "***",
            "hide_client_secret": true,
            "username": "***",
            "password": "***",
            "hide_password": true,
            "platform": "netatmo-security",
            "_bridge": {
                "username": "***",
                "port": ***
            }
        }```

**Environment:**

* **Plugin Version**: homebridge-netatmo-security v1.2.1
* **Homebridge Version**:  1.5.0
* **Node.js Version**: v16.13.2
* **NPM Version**: 8.1.2
* **Operating System**: Docker Alpine Linux (3.12.9)

**Comment by Anzure** [comment]
This plugin does not currently support Outdoor Camera. I do not have the accessory myself, so I cannot test alone. Are you making a plugin? I can take a look, if you send me the source code?

**Comment by appolonien** [comment]
Hello Anzure and thank you for this plugin.
I think I’m not to far to succes :), the authentication is ok but I have the same error as jmjjlai about "reading ‘home’".

could you help me with this please ? I’m sorry I’m really a beginner here…
Thank you. 

here are my errors:

` TypeError: Cannot read properties of undefined (reading 'home')
at NetatmoAPI. getHomeStatus (/homebridge/node modules/homebridge-netatmo-security/src/util/NetatmoAPI. js
:102:25 )
at processticksAndRejections (node: internal/process/task queues :95:5)
at NetatmoAPI. getHomeDevices (/homebridge/node modules /homebridge-netatmo-security/src/util/NetatmoAPI. j
s:110:20 )`
