### ISSUE TITLE
Not working anymore > See error

### ISSUE THREAD

**Issue by Stefan0568** [anzure/homebridge-netatmo-security#17]
It is not working anymore. Tried: Restart; New installation; New ClientID and Secret.
See below error.

[18/07/2023, 10:18:13] [Netatmo Security Platform] Restarting Process...
[18/07/2023, 10:18:14] [Netatmo Security Platform] Launched child bridge with PID 22938
[18/07/2023, 10:18:14] Registering platform 'homebridge-netatmo-security.netatmo-security'
[18/07/2023, 10:18:14] [Netatmo Security Platform] Loaded homebridge-netatmo-security v1.2.1 child bridge successfully
[18/07/2023, 10:18:14] [Netatmo Security Platform] Netatmo API constructed.
[18/07/2023, 10:18:15] Homebridge v1.6.1 (HAP v0.11.1) (Netatmo Security Platform) is running on port 45332.

/var/lib/homebridge/node_modules/homebridge-netatmo-security/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^
Error: Request failed with status code 400
    at createError (/var/lib/homebridge/node_modules/homebridge-netatmo-security/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/lib/homebridge/node_modules/homebridge-netatmo-security/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-netatmo-security/node_modules/axios/lib/adapters/http.js:312:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[18/07/2023, 10:18:15] [Netatmo Security Platform] Child bridge process ended
[18/07/2023, 10:18:15] [Netatmo Security Platform] Process Ended. Code: 1, Signal: null

**Comment by vbo-6600** [comment]
Hey

Get same issue… is there a way to solve ?  Or update ?
